version: "3.8"

services:
  init-volumes:
    image: alpine:3.18
    container_name: pocketd-volume-init
    command: chown -R 1025:1025 /data /config /keyring-test
    volumes:
      - pocketd_data:/data
      - pocketd_config:/config
    restart: "no"

  pocketd:
    build:
      context: .
    image: pocketd:v0.1.6
    container_name: pocketd-node
    user: 1025:1025
    entrypoint: ["bash", "/start-node.sh"]
    depends_on:
      - init-volumes
    restart: unless-stopped
    environment:
      - DAEMON_NAME=pocketd
      - DAEMON_HOME=/home/pocket/.pocket
      - DAEMON_RESTART_AFTER_UPGRADE=true
      - DAEMON_ALLOW_DOWNLOAD_BINARIES=true
      - UNSAFE_SKIP_BACKUP=true
      - NETWORK=
      - EXTERNAL_IP=
      - NODE_MONIKER=
      - POCKETD_LOG_LEVEL=info
      - USE_SNAPSHOT=true
    ports:
      - "26656:26656"  # P2P
      - "26657:26657"  # RPC
      - "26660:26660"  # Prometheus metrics
    volumes:
      - pocketd_data:/home/pocket/.pocket/data
      - pocketd_config:/home/pocket/.pocket/config
      - pocketd_keyring:/home/pocket/.pocket/keyring-test

volumes:
  pocketd_data:
  pocketd_config:
  pocketd_keyring:
