version: "3.8"

services:
  init-volumes:
    image: alpine:3.18
    container_name: pocketd-volumes-init
    command: chown -R 1025:1025 /data /relayminer
    volumes:
      - pocketd_home:/data
      - relayminer_home:/relayminer
    restart: "no"

  pocketd:
    build:
      context: .
    image: pocketd:v0.1.26
    container_name: pocketd-node
    user: 1025:1025
    entrypoint: ["bash", "/scripts/start-node.sh"]
    depends_on:
      - init-volumes
    restart: unless-stopped
    environment:
      - DAEMON_NAME=pocketd
      - DAEMON_HOME=/home/pocket/.pocket
      - DAEMON_RESTART_AFTER_UPGRADE=true
      - DAEMON_ALLOW_DOWNLOAD_BINARIES=true
      - UNSAFE_SKIP_BACKUP=true
      - NETWORK=
      - EXTERNAL_IP=
      - NODE_MONIKER=
      - POCKETD_LOG_LEVEL=info
      - USE_SNAPSHOT=true
      - SNAPSHOT_TYPE=archival
    ports:
      - "9090:9090"    # GRPC
      - "1317:1317"    # API
      - "26656:26656"  # P2P
      - "26657:26657"  # RPC
      - "26660:26660"  # Prometheus metrics
    volumes:
      - pocketd_home:/home/pocket/.pocket

  relayminer:
    image: pocketd:v0.1.26
    container_name: relayminer
    user: 1025:1025
    entrypoint: ["bash", "/scripts/start-relayminer.sh"]
    restart: "no"
    environment:
      - PATH=/usr/local/cosmovisor/genesis/bin:$PATH
      - CHAIN_ID=
      - ENABLE_RELAYMINER=false
      - KEYRING_BACKEND=
    ports:
      - "8545:8545"  # RPC
      - "9000:9000"  # Prometheus metrics
    depends_on:
      - pocketd
    volumes:
      - relayminer_home:/home/pocket/.pocket

volumes:
  pocketd_home:
  relayminer_home:
