default_signing_key_names:
  - <operator_key_name> # name of the operator key in the keyring
default_request_timeout_seconds: 25
default_max_body_size: 30MB
smt_store_path: ":memory:"
enable_over_servicing: true
pocket_node:
  query_node_rpc_url: tcp://pocketd-node:26657
  query_node_grpc_url: tcp://pocketd-node:9090
  tx_node_rpc_url: tcp://pocketd-node:26657
suppliers:
  - service_id: <service_id> # target blockchain service id (e.g. eth)
    listen_url: http://0.0.0.0:8545
    service_config:
      backend_url: <service_rpc_url> # RPC endpoint of the target blockchain
metrics:
  enabled: true
  addr: :9000
pprof:
  enabled: false
  addr: localhost:6060
ping:
  enabled: false
  addr: localhost:8081
